PREFIX ex: <http://example.org/mobility#>

SELECT ?congestion (AVG(?delay) AS ?avgDelay)
WHERE {
  ?bus a ex:Bus ;
       ex:locatedIn ?zone ;
       ex:delayMinutes ?delay .

  ?t a ex:Traffic ;
     ex:locatedIn ?zone ;
     ex:congestionLevel ?congestion .
}
GROUP BY ?congestion
ORDER BY DESC(?avgDelay)
